### ISSUE TITLE
Test flow uses Python 3

### ISSUE THREAD

**Issue by BradleyBoutcher** [cyberark/ansible-conjur-host-identity#41]
## Is your feature request related to a problem? Please describe.

Python 2 has been at EOL since January

## Describe the solution you would like

Our test flow should be modified to use Python 3 over Python 2 for future-proofing

## Additional context

Issue was noticed while resolving #39

**Comment by izgeri** [comment]
@BradleyBoutcher I remember you mentioned something about updating this - is this still an open issue?

**Comment by BradleyBoutcher** [comment]
@izgeri This upgrade was performed with PR #40, I'll close this issue
